# Put your personal spotify login here. Mopidy needs it to access
# spotify but will not share it with anyone.
spotify_user: ""
spotify_password: ""

# Refer to the excellent docs of
# mopidy spotify https://mopidy.com/ext/spotify/#authentication
# on how to get the right values here
spotify_client_id: ""
spotify_client_secret: ""
